---

- name: jenkins restart
  service: name=jenkins state=restarted
  sudo: yes
  notify: jenkins wait for CLI

- name: jenkins wait for CLI
  shell: curl --head --silent http://{{ jenkins_http_host }}:{{ jenkins_http_port }}{{ jenkins_prefix }}/cli/
  delay: 5
  retries: 12
  register: result
  until: result.stdout.find("200 OK") != -1

- name: jenkins update jobs
  command: "{{jenkins_home}}/jobs/job.sh {{item.item.name}}"
  sudo_user: "{{ jenkins_user }}"
  when: item.changed
  with_items: jenkins_jobs_changed.results

- name: jenkins reload configuration
  command: java -jar {{jenkins_home}}/jenkins-cli.jar -s http://{{jenkins_http_host}}:{{jenkins_http_port}}{{jenkins_prefix}} reload-configuration
  sudo_user: "{{ jenkins_user }}"

- name: nginx reload
  service: name=nginx state=reloaded
  sudo: yes

- name: apache restart
  service: name=apache2 state=restarted
  sudo: yes
